name: Main

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CACHE: true

jobs:
  changes:
    name: Detect changes
    runs-on: ubuntu-latest
    outputs:
      any: ${{ steps.changes.outputs.any }}
      programs: ${{ steps.changes.outputs.programs }}
      program_matrix: ${{ steps.program_matrix.outputs.matrix }}
      js_client: ${{ steps.changes.outputs.js_client }}
      rust_client: ${{ steps.changes.outputs.rust_client }}
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Load environment variables
        run: cat .github/.env >> $GITHUB_ENV

      - name: Detect changes
        uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: .github/file-filters.yml

      - name: Filter program matrix
        id: program_matrix
        uses: metaplex-foundation/actions/filter-matrix@v1
        with:
          matrix: ${{ env.PROGRAMS }}
          changes: ${{ steps.changes.outputs.changes }}
          suffix: _program

  build_programs:
    name: Programs
    if: ${{ needs.changes.outputs.any == 'true' }}
    needs: changes
    uses: ./.github/workflows/build-programs.yml
    secrets: inherit

  test_programs:
    name: Programs
    if: ${{ needs.changes.outputs.programs == 'true' }}
    needs: changes
    uses: ./.github/workflows/test-programs.yml
    secrets: inherit
    with:
      program_matrix: ${{ needs.changes.outputs.program_matrix }}